### ISSUE TITLE
Ошибка в дате, не закачивает следующие записи в логе.

### ISSUE THREAD

**Issue by 1rV1N-git** [akpaevj/OneSTools.EventLog#13]
```
crit: OneSTools.EventLog.Exporter.Manager.ExportersManager[0]
      Failed to execute EventLogExporter
      System.FormatException: String '20210C24080913' was not recognized as a valid DateTime.
         at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
         at OneSTools.EventLog.LgpReader.ParseEventLogItemData(StringBuilder eventLogItemData, Int64 endPosition, CancellationToken cancellationToken)
         at OneSTools.EventLog.LgpReader.ReadEventLogItemData(CancellationToken cancellationToken)
         at OneSTools.EventLog.LgpReader.ReadNextEventLogItem(CancellationToken cancellationToken)
         at OneSTools.EventLog.EventLogReader.ReadNextEventLogItem(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.Core.EventLogExporter.StartAsync(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.Manager.ExportersManager.<>c__DisplayClass22_0.<<StartExporter>b__0>d.MoveNext()
```

**Comment by akpaevj** [comment]
Можно такие записи пропускать с обязательным выводом в лог приложения
