### ISSUE TITLE
Вылетает программа

### ISSUE THREAD

**Issue by 1rV1N-git** [akpaevj/OneSTools.EventLog#14]
В случайные периоды вылетает прогрмма.
Возможно это когда 1с что то пищет в этот фал или во время рестарта службы 1с.
```
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Program Files\1cv8\srvinfo\reg_1541\1CV8Clst.lst'.
File name: 'C:\Program Files\1cv8\srvinfo\reg_1541\1CV8Clst.lst'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at OneSTools.EventLog.Exporter.Manager.ClstWatcher.ReadInfoBases()
   at OneSTools.EventLog.Exporter.Manager.ClstWatcher.ReadInfoBasesAndRaiseEvents()
   at OneSTools.EventLog.Exporter.Manager.ClstWatcher.ClstWatcher_Changed(Object sender, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

**Comment by akpaevj** [comment]
С этим надо плотнее разбираться. Предполагаю, что менеджер кластера пересоздает файл при перезапуске службе

**Comment by deevil** [comment]
Актуально)


```
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Program Files\1cv8\srvinfo\reg_1541\1CV8Clst.lst'.
File name: 'C:\Program Files\1cv8\srvinfo\reg_1541\1CV8Clst.lst'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at OneSTools.EventLog.Exporter.Manager.ClstWatcher.ReadInfoBases()
   at OneSTools.EventLog.Exporter.Manager.ClstWatcher.ReadInfoBasesAndRaiseEvents()
   at OneSTools.EventLog.Exporter.Manager.ClstWatcher.ClstWatcher_Changed(Object sender, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

```
