### ISSUE TITLE
Сбой при чтении ЖР

### ISSUE THREAD

**Issue by EvilBeaver** [akpaevj/OneSTools.EventLog#22]
Процесс 1С был убит из Диспетчера Задач, в этот момент он писал в ЖР. Вероятно, ЖР немного побился, но сама 1С ничего не замечает и продолжает с ним работать, однако экспортер спотыкается:

```
File 20210607000000.lgp will be read from 115419 position, LGF file will be read from 5647 position
collector_1   | crit: OneSTools.EventLog.Exporter.EventLogExporterService[0]
collector_1   |       Failed to execute EventLogExporter
collector_1   |       System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
collector_1   |          at System.Collections.Generic.List`1.get_Item(Int32 index)
collector_1   |          at OneSTools.BracketsFile.BracketsNode.get_Item(Int32 index)
collector_1   |          at OneSTools.EventLog.LgpReader.ParseEventLogItemData(StringBuilder eventLogItemData, Int64 endPosition, CancellationToken cancellationToken)
collector_1   |          at OneSTools.EventLog.LgpReader.ReadEventLogItemData(CancellationToken cancellationToken)
collector_1   |          at OneSTools.EventLog.LgpReader.ReadNextEventLogItem(CancellationToken cancellationToken)
collector_1   |          at OneSTools.EventLog.EventLogReader.ReadNextEventLogItem(CancellationToken cancellationToken)
collector_1   |          at OneSTools.EventLog.Exporter.Core.EventLogExporter.StartAsync(CancellationToken cancellationToken)
collector_1   |          at OneSTools.EventLog.Exporter.EventLogExporterService.ExecuteAsync(CancellationToken stoppingToken)
```

Сбойный журнал прилагаю.

[1Cv8Log.zip](https://github.com/akpaevj/OneSTools.EventLog/files/6607744/1Cv8Log.zip)

Ожидаемое поведение: экспортер сигнализирует об ошибке, но не прекращает работу.

**Comment by akpaevj** [comment]
Такая проблема действительно есть (примерно то же что и в #14), принято к исправлению

**Comment by EvilBeaver** [comment]
Нужен какой-то алгоритм Recovery, чтобы восстанавливаться после ошибки парсинга записи журнала. В особо тяжелых случаях - инструкция, как переставить указатель чтения за некорректный участок.

**Comment by milanse** [comment]
А вот у меня вариант хуже получился, тупо висит, ничего никуда не пишет, не ругается. Может есть возможность какую-то доп отладочную инфу глянуть ?
