### ISSUE TITLE
Не создается шаблон индекса в ES

### ISSUE THREAD

**Issue by nagdevops2** [akpaevj/OneSTools.EventLog#36]
Здравствуйте.

При первом запуске получаю ошибку:

crit: OneSTools.EventLog.Exporter.EventLogExporterService[0]
      Failed to execute EventLogExporter
      Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /_index_template/oneslogs. ServerError: Type: illegal_argument_exception Reason: "index template [oneslogs] has index patterns [*-el-*] matching patterns from existing templates [.kibana-event-log-7.16.2-template,journal_reg,onectj_top20,onectjbpnew,onectjsapp2,v8hasp] with patterns (.kibana-event-log-7.16.2-template => [.kibana-event-log-7.16.2-*],journal_reg => [journal_reg-*],onectj_top20 => [onectj_top20-*],onectjbpnew => [onectjbpnew-*],onectjsapp2 => [onectjsapp2-*],v8hasp => [v8hasp-*]) that have the same priority [0], multiple index templates may not match during index creation, please use a different priority"
         at OneSTools.EventLog.Exporter.Core.ElasticSearch.ElasticSearchStorage.CreateIndexTemplateAsync(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.Core.ElasticSearch.ElasticSearchStorage.ConnectAsync(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.Core.ElasticSearch.ElasticSearchStorage.ReadEventLogPositionAsync(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.Core.EventLogExporter.GetReaderSettingsAsync(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.Core.EventLogExporter.StartAsync(CancellationToken cancellationToken)
         at OneSTools.EventLog.Exporter.EventLogExporterService.ExecuteAsync(CancellationToken stoppingToken)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

Не нравится index patterns [*-el-*]  , как то можно обойти эту ошибку?

**Comment by fotov** [comment]
у меня такая-же проблема

решилось добавлением шаблона в кибане вручную через dev-tools (наименование шаблона поставил 1c-log-*)

PUT /_index_template/oneslogs
{
  "index_patterns": "1c-log-*",
  "template": {
    "mappings": {
      "properties": {
        "Id": {
          "type": "long"
        },
        "addPort": {
          "type": "integer"
        },
        "application": {
          "type": "keyword"
        },
        "comment": {
          "type": "text"
        },
        "computer": {
          "type": "keyword"
        },
        "connection": {
          "type": "long"
        },
        "data": {
          "type": "text"
        },
        "dataPresentation": {
          "type": "text"
        },
        "dateTime": {
          "type": "date"
        },
        "endPosition": {
          "type": "long"
        },
        "event": {
          "type": "keyword"
        },
        "fileName": {
          "type": "keyword"
        },
        "lgfEndPosition": {
          "type": "long"
        },
        "mainPort": {
          "type": "integer"
        },
        "metadata": {
          "type": "keyword"
        },
        "metadataUuid": {
          "type": "keyword"
        },
        "server": {
          "type": "keyword"
        },
        "session": {
          "type": "long"
        },
        "severity": {
          "type": "keyword"
        },
        "transactionDateTime": {
          "type": "date"
        },
        "transactionNumber": {
          "type": "long"
        },
        "transactionStatus": {
          "type": "keyword"
        },
        "user": {
          "type": "keyword"
        },
        "userUuid": {
          "type": "keyword"
        }
      }
    },
    "settings": {
      "index.codec": "best_compression"
    }
  }
}
